const AI_BASE='https://future-stars-ai-backend.onrender.com';
let clipObjectUrl='',chatBusy=false,previewListener=null;
const $=id=>document.getElementById(id);
function addMessage(text,type){const el=document.createElement('div');el.className='message '+type;el.textContent=text;$('chatMessages').append(el);$('chatMessages').scrollTop=$('chatMessages').scrollHeight;return el;}
function setStatus(text){$('statusBox').style.display='block';$('statusBox').textContent=text;}
function setReport(text){$('reportBox').textContent=text||'Your report will appear here after analysis.';}
async function api(path,options){const control=new AbortController();const timer=setTimeout(()=>control.abort(),180000);try{const response=await fetch(AI_BASE+path,{...options,signal:control.signal});if(!response.ok)throw new Error('Request failed');return response;}finally{clearTimeout(timer);}}
function selectedVideos(){const side=$('sideVideo').files[0],back=$('backVideo').files[0];if(!side||!back){setStatus('Please choose both a side-view and a back-view video.');return null;}const data=new FormData();data.append('sideVideo',side);data.append('backVideo',back);return data;}
function analysisBusy(busy){for(const id of ['generateReportButton','pdfButton','sideVideo','backVideo','clearButton'])$(id).disabled=busy;}
async function sendChatMessage(){if(chatBusy)return;const text=$('chatInput').value.trim();if(!text)return;chatBusy=true;$('chatSend').disabled=true;addMessage(text,'user');$('chatInput').value='';const reply=addMessage('Thinking…','ai');try{const r=await api('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const data=await r.json();reply.textContent=data.reply||'No reply was returned. Please try again.';}catch{reply.textContent='The assistant is unavailable right now. Please try again in a minute.';}finally{chatBusy=false;$('chatSend').disabled=false;}}
async function generateAIReport(){const data=selectedVideos();if(!data)return;analysisBusy(true);$('generateReportButton').textContent='Reviewing…';setStatus('Reviewing your clips. This may take a minute.');setReport('');try{const r=await api('/api/analyze-video',{method:'POST',body:data});const result=await r.json();if(!result.report)throw new Error('Empty report');setReport(result.report);setStatus('Your report is ready.');}catch{setStatus('We couldn’t generate the report. Try again in a minute, or use shorter clips.');}finally{analysisBusy(false);$('generateReportButton').textContent='Generate AI Report';}}
async function downloadPdfReport(){const data=selectedVideos();if(!data)return;analysisBusy(true);$('pdfButton').textContent='Preparing PDF…';setStatus('Preparing a PDF with selected video frames. This may take a minute.');try{const r=await api('/api/analyze-video-pdf',{method:'POST',body:data});const blob=await r.blob();if((await blob.slice(0,5).text())!=='%PDF-')throw new Error('Invalid PDF');download(blob,'future-stars-swing-report-'+new Date().toISOString().slice(0,10)+'.pdf');setStatus('Your PDF download has started.');}catch{setStatus('We couldn’t prepare the PDF. Try again in a minute, or use shorter clips.');}finally{analysisBusy(false);$('pdfButton').textContent='Download PDF';}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function clearReport(){$('sideVideo').value='';$('backVideo').value='';$('statusBox').style.display='none';setReport('');}
function loadClipVideo(){const file=$('clipVideoInput').files[0];if(!file)return;const video=$('clipVideoPreview');if(clipObjectUrl)URL.revokeObjectURL(clipObjectUrl);clipObjectUrl=URL.createObjectURL(file);video.src=clipObjectUrl;video.onloadedmetadata=()=>{$('clipStart').value='0';$('clipEnd').value=Math.min(5,video.duration).toFixed(1);$('clipStatus').textContent=`Video length: ${video.duration.toFixed(1)} seconds. Choose a 3–8 second clip.`;};video.onerror=()=>{$('clipStatus').textContent='This video cannot be previewed in your browser. Try an MP4 file.';};video.load();}
function getClipTimes(){const start=Number($('clipStart').value),end=Number($('clipEnd').value),duration=$('clipVideoPreview').duration;if(!$('clipVideoInput').files[0]){$('clipStatus').textContent='Choose a video first.';return null;}if(!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start||(Number.isFinite(duration)&&end>duration)){$('clipStatus').textContent='Enter valid start and end times within the video.';return null;}return {start,end};}
function previewClip(){const times=getClipTimes();if(!times)return;const video=$('clipVideoPreview');if(previewListener)video.removeEventListener('timeupdate',previewListener);previewListener=()=>{if(video.currentTime>=times.end){video.pause();video.removeEventListener('timeupdate',previewListener);}};video.addEventListener('timeupdate',previewListener);video.currentTime=times.start;video.play().catch(()=>{$('clipStatus').textContent='Press play on the video to preview.';});}
async function trimVideoOnBackend(){const times=getClipTimes();if(!times)return;if(times.end-times.start>30){$('clipStatus').textContent='Please choose 30 seconds or less. We recommend 3–8 seconds.';return;}const data=new FormData();data.append('video',$('clipVideoInput').files[0]);data.append('start',String(times.start));data.append('end',String(times.end));const button=$('trimClipButton');button.disabled=true;button.textContent='Trimming…';$('clipStatus').textContent='Preparing your shorter clip…';try{const r=await api('/api/trim-video',{method:'POST',body:data});download(await r.blob(),'future-stars-trimmed-clip.mp4');$('clipStatus').textContent='Download started. Choose the saved MP4 in the side-view or back-view upload above.';}catch{$('clipStatus').textContent='We couldn’t trim this video. Try again or choose a shorter video.';}finally{button.disabled=false;button.textContent='Trim & Download MP4';}}
$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.isComposing)sendChatMessage();});
